version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - vitalsync-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - vitalsync-network

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vitalsync-network

networks:
  vitalsync-network:
    driver: bridge

volumes:
  postgres_data: